### ISSUE TITLE
Sound stop mode on "Immediate" stops SS2's stirring soul drops from making their pickup sound

### ISSUE THREAD

**Issue by LordVGames** [Goorakh/LoopingSoundFix#1]
the sound from the pickups don't loop so idk why the mod is stopping them
if sound stop mode is on `nextloop` the sound plays fine

**Comment by Goorakh** [comment]
The Immediate stop mode stops all sounds associated with an object when it is removed, regardless of looping. This is how NextLoop works too. The mod makes no distinction between non-looping and looping sounds, since that can't be easily determined as far as I'm aware.

Not really a bug, more just unintuitive how it works I suppose.

Using "Immediate" is not recommended, frankly that setting should just be removed.
